export enum FineStatusEnum {
  NEW = 'NEW',
  PROCESSING_DOCUMENT = 'PROCESSING_DOCUMENT',
  READY_FOR_SIGNING = 'READY_FOR_SIGNING',
  PROCESSING_SIGNING = 'PROCESSING_SIGNING',
  READY_FOR_PAYMENT = 'READY_FOR_PAYMENT',
  PROCESSING_PAYMENT = 'PROCESSING_PAYMENT',
  PAID = 'PAID',
  CLOSED = 'CLOSED',
}
